[frontend]
frontend-vm ansible_host=136.115.68.28 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[backend]
backend-vm ansible_host=34.27.217.25 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[db]
mongodb-vm ansible_host=136.113.122.141 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa